- name: task level variables
  hosts: web
  vars:
    name: "mahesh cheerneni"
    cource: "Mahesh Devops"
  tasks:
    - name: Task level variables asssigned
      vars:
        name:"mahesh"
        cource:"Mahesh Chat Gpt"
      ansible.builtin.debug:
        msg: "The trainer name is {{name}} and course name is {{cource}}"
      
    - name: print information
      ansible.builtin.debug:
        msg: "The trainer name is {{name}} and course name is {{cource}}"